:numbered!:

== kubertweet is a fork of angrytweet running on Kubernetes/OpenShift3

This demo extends the usage of the docker images, provided in kubertweet/docker, to OpenShift V3.
 
For this demo we will be using the upstream version of OpenShift

=== Instructions for RHEL7

==== Install Docker 

Install docker as decribed in https://access.redhat.com/articles/881893. 

After this installation you will have docker and a local registry. 

Change the config of docker to make sure that your container see the web, kubertweet is using twitter.

----
# vi /etc/sysconfig/docker
# docker_OPTS="--dns a-dns-server"
----

==== Install OpenShift v3
Instruction are provided here : https://github.com/openshift/origin
 
Before building openshift, depending on its release, you might need to change the source that is in pkg/cmd/master/master.go and replace 127.0.0.1 by your local fixed ip address of your machine so the minion will listen on this address.

The kubernates service declared in kuber-tweet-mysql-service.json will provides to the containers the variable SERVICE_HOST that is the Ip of the minion that run the containers. If the minion is attached to 127.0.0.1 this will conflict with the loopback of the containers.

==== Build the containers
Then you will need to build the docker files. 

The docker files are in kubertweet/docker, in this build we are using the environnement variables injected in the container by kubernates. 
After starting the service declared in kuber-tweet-mysql-service.json the pods, related to the instances of Fuse Service Works (kuber-tweet-fsw.json) and rtGov (kuber-tweet-rtgov.json), will receive in there env the IP and port of the database in the variables SERVICE_HOST (the ip of the minion) and $ANGRYTWEETDB_PORT_3306_TCP_ADDR (the port of the services named angrytweetdb that routes the requests to the database pod).

Before building you should change the file start-fsw.sh contained in kubertweet/docker/fsw and put the right credentials for your twitter and mail services.


----
ANGRYTWEET_CONSUMERKEY=replace 
ANGRYTWEET_CONSUMERSECRET=replace 
ANGRYTWEET_ACCESSTOKEN=replace 
ANGRYTWEET_CONSUMERSECRET=replace 
ANGRYTWEET_EMAIL_USERNAME=replace 
ANGRYTWEET_EMAIL_PASSWORD=replace 
ANGRYTWEET_EMAIL_HOST="smtps://smtp.gmail.com:465"
----
The build is done using those instructions

----
# docker build -t kubertweet/fsw docker/fsw
# docker build -t kubertweet/mysql docker/mysql
# docker build -t kubertweet/rtgov docker/rtgov
----

After the build you need to add a tag the localimages so you can push them to the local registry for all 3 images

----
# docker images | grep fsw 
# docker tag image_id localhost:5000/kubertweet/fsw
# docker push localhost:5000/kubertweet/fsw
----

Kubernates will pull the container from the registry before starting it, so tagging the container with the address of the local registry will offer the possibility to run this demo offline without pushing (or pulling) the image to (from) docker.io.

==== Run the whole thing

Start openshift
----
# _output/go/bin/openshift start
----

Start the kunernates service
----
# _output/go/bin/openshift kube create services -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-mysql-service.json
----

Start the kubernates pod that contains the DB
----
# _output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-mysql.json
----

WAIT for DB, check that it is listeneing on port 3309 and 10000 (proxied by the kubernates services) 

----
# _output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-rtgov.json
# _output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-fsw.json
----

==== Checking the status of the pods
----
# _output/go/bin/openshift kube list pods
----

==== Stopping the pods

----
# _output/go/bin/openshift kube delete pods/kubertweetmysql
# _output/go/bin/openshift kube delete pods/kubertweetfsw
# _output/go/bin/openshift kube delete pods/kubertweetrtgov
# _output/go/bin/openshift kube delete services/kubertweetdb
----

==== Accessing the application
rtGov will be available on http://localhost:4080 for the admin console and on http://localhost:4080/gadget-web for the rtgov console.

Fuse Services works will be available on http://localhost:7080


