:numbered!:

== kubertweet Kubernates configuguration for OSE 3

This demo extend the usage of the docker images, provided in kubertweet/docker, to OpenShift V3. 

For this first run I will be using OpenShift v3 from .... 

=== Instructions on the top of RHEL7

==== Install Docker 

Install docker as decribed in https://access.redhat.com/articles/881893. After this install you will have docker and a local registry. 
Change the config of docker to make sure that your container see the web, kubertweet is using twitter.
vi /etc/sysconfig/docker
docker_OPTS="--dns a-dns-server"

==== Install OpenShift v3
Instruction are provided here https://github.com/openshift/origin
Note : Before building openshift you might need to change the source that is in pkg/cmd/master/master.go and replace 127.0.0.1 by your local fixed ip address to the minion will listen on this address. 
The kubernates service declared in  kuber-tweet-mysql-service.json will provide to the containers the variable SERVICE_HOST that hsi the Ip of the minion that rund the container.

==== Build the containers
Then you will need to build the docker files the instruction are provided in kubertweet/docker, in this build we are using the environnement variable injected in the container by kubernates. After starting the service declared in kuber-tweet-mysql-service.json the pods related to the instances of Fuse Service Works (kuber-tweet-fsw.json) and rtGov (kuber-tweet-rtgov.json) will receive in their env the IP and port of the database.

Added to those instruction and before building you should change the file start-fsw.sh contained in kubertweet/docker/fsw and put the right credentials for your twitter and mail services.


ANGRYTWEET_CONSUMERKEY=replace 
ANGRYTWEET_CONSUMERSECRET=replace 
ANGRYTWEET_ACCESSTOKEN=replace 
ANGRYTWEET_CONSUMERSECRET=replace 
ANGRYTWEET_EMAIL_USERNAME=replace 
ANGRYTWEET_EMAIL_PASSWORD=replace 
ANGRYTWEET_EMAIL_HOST="smtps://smtp.gmail.com:465" 


docker build -t kubertweet/fsw docker/fsw
docker build -t kubertweet/mysql docker/mysql
docker build -t kubertweet/rtgov docker/rtgov

tag the container so you can push them to the local registry

docker tag container_id localhost:5000/kubertweet/fsw
docker push localhost:5000/kubertweet/fsw

Note : Kubernates will pull the container from the registry before starting it, so tagging the container with the address of the localregistry will offer the possibility to run this demo offline without pushing (or pulling) the image to (from) docker.io.

==== Run the hole thing

Start openshift
_output/go/bin/openshift start

Start the kunernates service
_output/go/bin/openshift kube create services -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-mysql-service.json

Start the kubernates pod that contains the DB
_output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-mysql.json

WAIT for DB, check that it is listeneing on port 3309 and 10000 (proxied by the kubernates services) 

_output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-rtgov.json
_output/go/bin/openshift kube create pods -c /home/gabriel/kubertweet/kubernetes/kuber-tweet-fsw.json


==== Checking the status of the pods

_output/go/bin/openshift kube list pods

==== Stopping the pods

_output/go/bin/openshift kube delete pods/kubertweetmysql
_output/go/bin/openshift kube delete pods/kubertweetfsw
_output/go/bin/openshift kube delete pods/kubertweetrtgov
_output/go/bin/openshift kube delete services/kubertweetdb


