package org.jboss.demo.fsw.angrytweet.crm.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.6-redhat-3
 * 2014-01-28T11:38:11.504+01:00
 * Generated source version: 2.6.6-redhat-3
 * 
 */
@WebService(targetNamespace = "urn:crm:account-service:1.0", name = "AccountPortType")
public interface AccountService {

    @RequestWrapper(localName = "getAccountInfo", targetNamespace = "urn:crm:account-service:1.0", className = "org.jboss.demo.fsw.angrytweet.crm.model.GetAccountInfo")
    @WebMethod(action = "urn:crm:account-service:1.0:getAccountInfo")
    @ResponseWrapper(localName = "getAccountInfoResponse", targetNamespace = "urn:crm:account-service:1.0", className = "org.jboss.demo.fsw.angrytweet.crm.model.GetAccountInfoResponse")
    public void getAccountInfo(
        @WebParam(name = "account", targetNamespace = "")
        org.jboss.demo.fsw.angrytweet.crm.model.Account account,
        @WebParam(mode = WebParam.Mode.OUT, name = "result", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Boolean> result,
        @WebParam(mode = WebParam.Mode.OUT, name = "reason", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> reason,
        @WebParam(mode = WebParam.Mode.OUT, name = "account", targetNamespace = "")
        javax.xml.ws.Holder<java.util.List<org.jboss.demo.fsw.angrytweet.crm.model.Account>> accountList
    );
}
