//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.29 at 12:14:32 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:crm:account-service:1.0")
package org.jboss.demo.fsw.angrytweet.crm.model;
